'use client';
import MuiThemeProvider from '@/theme/Muithemeprovider';
import {Provider} from 'react-redux';
import { Inter } from 'next/font/google'
import store from '@/store';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
    <body className={inter.className} style={styles.body}>
    <Provider store={store}>
    <MuiThemeProvider>
     {children}
    </MuiThemeProvider>
    </Provider>
      </body>
    </html>
  )
}

const styles={
  body:{
  margin:'0px',
  }
}